sudo: enabled
dist: xenial
language: cpp
os: linux

cache:
  directories:
  - /opt/boost_1_66_0


matrix:
  include:
    - compiler: gcc
      env:
        - COMPILER=g++-5 LSAN_OPTIONS=suppressions=$HOME/supress.txt


before_install:
  # Fix for Ubuntu Xenial apt-daily.service triggering
  # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
  - |
    sudo systemctl stop apt-daily.service &&
    sudo systemctl kill --kill-who=all apt-daily.service &&
    while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
      sleep 1
    done
  - sudo apt update -qq

install:
  - ps aux | grep apt
  - sudo ./install-dependencies.sh

script:
  - printf "leak:MallocExtension\nleak:event_base_once" > $HOME/supress.txt
  - env && cat $HOME/supress.txt
  - mkdir testresults && ./blaze.sh -ninja && cd build-dbg
  - ninja -j4 base
  - tests_list=$(ctest -L CI -N | grep "Test.*#" | cut -f2 -d:| sort)
  - ninja -j4 $tests_list -k 10
  - echo $tests_list |  xargs -n1 -t ../scripts/run_test.sh -l ../testresults -t 25 --name

after_failure:
  - pwd
  - find ../third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
  - find ../testresults | xargs -n 3 -t cat
