sudo: enabled
dist: xenial
language: cpp
os: linux

cache:
  directories:
  - /opt/boost_1_66_0

env:
  - LSAN_OPTIONS=suppressions=$HOME/supress.txt


matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5


before_install:
  - sudo apt update -qq

install: sudo ./install-dependencies.sh

script:
  - printf "leak:MallocExtension\nleak:event_base_once" > $HOME/supress.txt
  - mkdir testresults && ./blaze.sh -ninja && cd build-dbg
  - ninja -j4 base
  - tests_list=$(ctest -L CI -N | grep "Test.*#" | cut -f2 -d:| sort)
  - ninja -j4 $tests_list -k 10
  - echo $tests_list |  xargs -n1 -t ../scripts/run_test.sh -l ../testresults -t 25 --name

after_failure:
  - pwd
  - find ../third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
  - find ../testresults | xargs -n 3 -t cat
