sudo: enabled
dist: xenial
language: cpp
os: linux

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5


before_install:
  - sudo apt update -qq

install: sudo ./install-dependencies.sh

script:
  - ./blaze.sh -ninja
  - cd build-dbg
  - ninja -j4 base
  - ninja -j4 bits_test fiber_demo

after_failure:
  - pwd
  - find ../third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
