sudo: enabled
dist: xenial
language: cpp
os: linux

env:
  global:
    - LSAN_OPTIONS=suppressions=$HOME/supress.txt

cache:
  directories:
  - /opt/boost_1_69_0
  - build-dbg/third_party  # Relative to $TRAVIS_BUILD_DIR

before_cache:
  - ls $TRAVIS_BUILD_DIR/build-dbg/third_party

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  # Fix for Ubuntu Xenial apt-daily.service triggering
  # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
  - |
    sudo systemctl stop apt-daily.timer
    sudo systemctl stop apt-daily.service &&
    sudo systemctl kill --kill-who=all apt-daily.service
    while (pgrep -cf apt.systemd.daily > /dev/null); do
      sleep 1
    done
  - sudo apt update -qq
  - eval "${MATRIX_EVAL}"

install:
  - sudo ./install-dependencies.sh
  - ls -l /opt/

script:
  - printf "leak:MallocExtension\nleak:event_base_once" > $HOME/supress.txt
  - cmake --version
  - env
  - mkdir testresults && mkdir -p build-dbg && cd build-dbg
  - cmake -L -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/ccache ..
  - ninja -j4 base array_test
  - tests_list=$(ctest -L CI -N | grep "Test.*#" | cut -f2 -d:| sort)
  - ninja -j4 $tests_list asio_fibers -k 10
  - ./http_test --logtostderr --vmodule=http_client=1
  - echo $tests_list |  xargs -n1 -t ../scripts/run_test.sh -l ../testresults -t 25 --name

after_failure:
  - pwd
  - find third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
  - find ../testresults | xargs -n 3 -t cat
